version: '3'
services:
    server:
        build: .
        environment:
            - SLACK_API_TOKEN
            # debug
            # - FLASK_APP=whistleblower_bot.server_app:app
        ports:
        - "5000:5000"
        links:
        - redis
        command: gunicorn -w 4 -b 0.0.0.0:5000 whistleblower_bot.server_app:app
        # debug
        # command: python -m flask run --host=0.0.0.0
    redis:
        image: redis
    celery:
        build: .
        environment:
            - SLACK_API_TOKEN
        links:
        - redis
        command: celery -A whistleblower_bot.tasks:app worker -l info
